-- WEATHER OBSERVATION 8 Q

SELECT DISTINCT CITY
FROM STATION
WHERE REGEXP_LIKE(CITY, '^[aeiou]', 'i')
  AND REGEXP_LIKE(CITY, '[aeiou]$', 'i')

-- WEATHER OBSERVATION 12 Q

SELECT DISTINCT CITY
FROM STATION
WHERE REGEXP_LIKE (CITY, '^[^aeiou]', 'i')
  AND REGEXP_LIKE (CITY, '[^aeiou]$', 'i')


